### ISSUE TITLE
A simple coding typo in `pagelabelscheme.py`

### ISSUE THREAD

**Issue by chifongwong** [lovasoa/pagelabels-py#11]
In line 15, the last item of the dictionary should be `"none": None` but now it is `"none", None`.

**Comment by lovasoa** [comment]
ooops, yes. This was introduced in https://github.com/lovasoa/pagelabels-py/pull/9 by @iliorik . I should not have merged blindly :grimacing:

**Comment by chifongwong** [comment]
Thanks your package, it's helping me a lot!

**Comment by iliorik** [comment]
Pardon. I was inattentive
