### ISSUE TITLE
--type none still not available in the latest PyPI release

### ISSUE THREAD

**Issue by stroobandt** [lovasoa/pagelabels-py#12]
I installed the latest `pagelabels` version available from the Python Package Index (PyPI).
Unfortunately, the option `--type none` is still not available in the [latest PyPI version](https://pypi.org/project/pagelabels/#history).
Thank you for upgrading the PyPI release.

**Comment by aprs434** [comment]
I am experiencing the same issue; Would love to see release 1.2.1 on PyPI!

**Comment by yilu1015** [comment]
Same issue here. Please update the PyPI release!

**Comment by lovasoa** [comment]
Ok, I'm 2 years late, but here it is :)

**https://pypi.org/project/pagelabels/#history**
