### ISSUE TITLE
The script does not work

### ISSUE THREAD

**Issue by muzimuzhi** [lovasoa/pagelabels-py#2]
I tried the script with this LaTeX-generated file [dummy-doc.pdf](https://github.com/lovasoa/pagelabels-py/files/2582354/dummy-doc.pdf), but nothing happens. 

The options I used are
```bash
./addpagelabels.py --startpage 1 --type "roman uppercase" --prefix "text" --firstpagenum 1 dummy-doc.pdf
```

I have also tried full path to the file, neither works.

Some version info:
 - macOS 10.14.1
 - python 3.7.1, installed through homebrew
 - pdfrw 0.4, installed through pip3

Would you please give me some advice on solving this problem, or suggestions about alternative pdf-page-label-changing tools? Thanks.

**Comment by lovasoa** [comment]
The script does work, but the original file is not overwritten. The result is written to `/tmp/test.pdf`.
I admit that this behavior is quite confusing, and undocumented. I am going to close this issue and create a new one for changing this behavior.

**Comment by lovasoa** [comment]
See #3

**Comment by lovasoa** [comment]
@muzimuzhi I also updated the [README](https://github.com/lovasoa/pagelabels-py/blob/master/README.md#pagelabels) in the hope you will find it useful.

**Comment by muzimuzhi** [comment]
It works now, thanks.
