### ISSUE TITLE
Export/Import

### ISSUE THREAD

**Issue by schmidhauser** [lovasoa/pagelabels-py#7]
It would be great if you could add an option to export and import a simple text file containing all labels. This would allow one easily to copy a book’s numeration from one PDF to another – say when one has a better version of it.

**Comment by lovasoa** [comment]
Good idea! Pull requests are welcome 😊

**Comment by lovasoa** [comment]
You can now copy the page labeling scheme from source.pdf and apply it to target.pdf with :

```
python3 -m pagelabels --load source.pdf target.pdf
```

**Comment by schmidhauser** [comment]
Great. With a single shortcut (and the help of a little Automator workflow) I can transfer the numeration from one PDF to another – I’ve been wanting to do this for so long. Thank you very much!
