### ISSUE TITLE
Folio Numeration

### ISSUE THREAD

**Issue by schmidhauser** [lovasoa/pagelabels-py#8]
It would be great if you could an option for numbering non-consecutive pages and more specifically for numbering only odd or only even pages. This would be extraordinarily useful for anyone dealing with medieval manuscripts and incunabula where one counts sheets or folios.

Another interesting addition would be an option `--postfix`. (Or perhaps use `--append`, together with `--prepend` instead of `--prefix`?) This would allow one to have recto and verso pages – 1r, 1v, 2r, 2v, etc.

**Comment by lovasoa** [comment]
Hello, 
  The PDF format has no option to do that. Your only option is to use a custom prefix for each page.

**Comment by schmidhauser** [comment]
As regards my first point, something along these lines appears to be possible. See e.g. https://github.com/johnwhitington/cpdf-source/issues/184.

**Comment by lovasoa** [comment]
Yes, it's possible and it's done exactly in the way I described above: adding one labelling scheme per page.
